# LeadFlowX Auditor
# Updated to use centralized configuration and templates

version: '3.8'

# Import shared templates from docker-compose.templates.yml
# Note: This service extends the shared templates

services:
  leadflowx-auditor:
    build: .
    <<: *default-restart
    <<: *default-logging
    networks: *default-networks
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DB_URL=${DB_URL}
      - KAFKA_BROKER=${KAFKA_BROKER:-kafka:29092}
      - PAGESPEED_API_KEY=${PAGESPEED_API_KEY}
      - SSL_CHECK_ENABLED=${SSL_CHECK_ENABLED:-true}
      - SEO_CHECK_ENABLED=${SEO_CHECK_ENABLED:-true}
      - MOBILE_CHECK_ENABLED=${MOBILE_CHECK_ENABLED:-true}
    ports:
      - "${AUDITOR_PORT:-8084}:${AUDITOR_INTERNAL_PORT:-8080}"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${AUDITOR_INTERNAL_PORT:-8080}/health"]
      <<: *healthcheck-base

networks:
  leadflowx-network:
    external: true
