version: '3.8'

services:
  leadflowx-auditor:
    build: .
    environment:
      - PAGESPEED_API_KEY=your-pagespeed-api-key-here
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/leadflowx
    depends_on:
      - postgres
    networks:
      - leadflowx-network
    ports:
      - "8081:8080"

networks:
  leadflowx-network:
    external: true
